name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Hämtar koden från repot
    - uses: actions/checkout@v4

    # Ställer in .NET version 8
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    # Bygger projektet och sparar filerna i mappen publish.
    # Pekar på csproj filen för att undvika fel med solution filen.
    - name: Publish application
      run: dotnet publish ExaminationApi/ExaminationApi/ExaminationApi.csproj -c Release -o ./publish

    # Zippar ihop filerna inför uppladdning
    - name: Create Zip file
      run: |
        cd publish
        zip -r ../deploy.zip .

    # Skickar upp zip filen till AWS miljön
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ExaminationApiV3
        environment_name: ExaminationApiV3-env
        version_label: "ver-${{ github.sha }}"
        region: eu-north-1
        deployment_package: deploy.zip